/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ChatComponent: typeof import('./src/components/ChatComponent.vue')['default']
    ChatTabs: typeof import('./src/components/ChatTabs.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    MessageDisplayComponent: typeof import('./src/components/MessageDisplayComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendButtonText: typeof import('./src/components/SendButtonText.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
  }
}
